# .github/workflows/deploy-backup.yml
name: Deploy Backup Solution

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        account-type: ['central', 'member']
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - run: npm ci
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets[format('%s_AWS_ACCESS_KEY_ID', matrix.account-type)] }}
          aws-secret-access-key: ${{ secrets[format('%s_AWS_SECRET_ACCESS_KEY', matrix.account-type)] }}
          aws-region: us-east-1
          
      - name: Deploy Stack
        run: |
          if [ "${{ matrix.account-type }}" == "central" ]; then
            npx cdk deploy CentralBackupStack
          else
            npx cdk deploy MemberBackupStack
          fi
